FROM mcr.microsoft.com/playwright:v1.45.0-jammy

WORKDIR /app

COPY api/package*.json ./api/

WORKDIR /app/api
RUN npm install --omit=dev
RUN npx playwright install --with-deps chromium

COPY api/ /app/api/

CMD ["node", "worker.js"]
